// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Usamos sempre a mesma URL (POSTGRES_URL) tanto local quanto na Vercel.
    // Em dev, defina POSTGRES_URL no .env com a mesma string usada em produção.
    // Para Prisma Postgres (db.prisma.io), forçamos pooled=true quando a URL não o tiver,
    // para evitar estourar limite de conexões no serverless (Vercel injeta URL sem pooled).
    url: (() => {
      let u = process.env["POSTGRES_URL"] ?? process.env["DATABASE_URL"] ?? process.env["PRISMA_DATABASE_URL"];
      if (!u || typeof u !== "string" || !u.startsWith("postgres")) {
        throw new Error(
          "URL do banco não configurada. No arquivo .env na raiz do projeto, defina POSTGRES_URL ou DATABASE_URL com a connection string do PostgreSQL (ex.: postgresql://usuario:senha@localhost:5432/nome_do_banco)"
        );
      }
      if (u.includes("db.prisma.io") && !u.includes("pooled=true")) {
        u += u.includes("?") ? "&pooled=true" : "?pooled=true";
      }
      return u;
    })(),
  },
});
