export { statsImpact } from "./stats";
export { parceiros } from "./parceiros";
export { faqItems } from "./faq";
export { depoimentos } from "./depoimentos";
export { projetosList, getProjetoBySlug } from "./projetos";
export type { ProjetoSlug } from "./projetos";
export { formaçõesDestaque, formaçõesPorAfinidade, comoFuncionaFormacao } from "./formacoes";
export { posts, postCategories, getPostBySlug, getAllSlugs } from "./posts";
export type { PostCategory } from "./posts";
export { documentos, categoriasTransparencia } from "./transparencia";
export type { CategoriaDocumento } from "./transparencia";
