ALTER TABLE "Reservation"
  ADD COLUMN IF NOT EXISTS "adultCourtesySelections" BOOLEAN[] NOT NULL DEFAULT ARRAY[]::BOOLEAN[],
  ADD COLUMN IF NOT EXISTS "childrenCourtesySelections" BOOLEAN[] NOT NULL DEFAULT ARRAY[]::BOOLEAN[];
